### ISSUE TITLE
LDAP auth support for Oracle connection

### ISSUE THREAD

**Issue by akhil** [joeferner/node-oracle#18]
Sorry for posting it as an issue.

Is there a way to connect to oracle DB using LDAP for auth?

**Comment by jdolan** [comment]
I'm in the same position @medokin was in: I have a JDBC URL specifying an LDAP lookup that I'd like to try to "port" for use with this driver. Assuming this is still unsupported?

**Comment by cjbj** [comment]
LDAP connectivity is handled by Oracle Net, so it's unlikely that node-oracle needs to have anything special implemented.  Both this unmaintained node-oracle driver (hint: don't use this for new work) and the new [node-oracledb](https://github.com/oracle/node-oracledb) driver use [OCI](http://docs.oracle.com/database/122/LNOCI/toc.htm#BEGIN) where the Oracle Net configuration files specify the LDAP connection, see http://stackoverflow.com/questions/31994159/how-do-you-connect-to-an-ldap-server-using-node-oracledb for the steps.
