### ISSUE TITLE
Running NPM as Root, Node Oracle Dies

### ISSUE THREAD

**Issue by deltreey** [joeferner/node-oracle#226]
The error is explicitly:
`Error: libocci.so.12.1: cannot open shared object file: No such file or directory`
The command I'm running is
`sudo -E npm start`
Note that `npm start` works perfectly well, provided I use a port above 1024.  But in order to run on port 80, I need to use sudo
The complete error is:

    module.js:356
    Module._extensions[extension](this, filename);
                                 ^
    Error: libocci.so.12.1: cannot open shared object file: No such file or directory
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/usr/local/executive-dashboards/node_modules/oracle/lib/oracle.js:2:16)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)

Here are my environment variables. Note that I even tried setting LD_LIBRARY_PATH, ORACLE_HOME, and my PATH as that is recommended elsewhere

    export ORACLE_HOME=/opt/instantclient_11_2
    
    export OCI_HOME=/opt/instantclient_11_2
    export OCI_LIB_DIR=$OCI_HOME
    export OCI_INCLUDE_DIR=$OCI_HOME/sdk/include
    export OCI_VERSION=12
    
    export PORT=80
    export PATH=$PATH:$ORACLE_HOME
    export LD_LIBRARY_PATH=$ORACLE_HOME:$OCI_INCLUDE_DIR:$LD_LIBRARY_PATH

yes, I changed instantclient_12_1 to instantclient_11_2 as part of my troubleshooting attempts

**Comment by a0viedo** [comment]
@deltreey how do you solved this issue?

**Comment by deltreey** [comment]
My linked files were not correct.  carefully go through the install of oracle OCI again, making sure you've set all the environment variables correctly and gotten all the symlinks right.  The issue is with th OCI install, not node-oracle.
