### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by danschumann** [joeferner/node-oracle#252]
There are changes in this repo my company is depending on and we must use this until oracle's official is better.  We don't want to point directly to github, so can you please `npm publish` the current state of this repo?

**Comment by cjbj** [comment]
@danschumann both projects would benefit from hearing where they could improve (and from getting PRs!)

**Comment by joeferner** [comment]
I honestly haven't kept up on this project at all. Are there any pull requests that should be merged before publishing?

Also would anyone like to have commit access to this project?

**Comment by danschumann** [comment]
@cjbj It's not me who is on the project that uses oracle, so I couldn't say for sure but I think it was some data type that was not supported.  For all we know it could be fixed in the official now.

**Comment by danschumann** [comment]
@cjbj also he says its stuck on a particular version of node ( or was ).  At the time it wasn't compiling on windows.  In the future though we plan to switch over.

**Comment by danschumann** [comment]
@cjbj We're giving the official another go and it seems promising this time.

**Comment by cjbj** [comment]
@danschumann Thanks for the update. If you have questions on the other driver, perhaps it would be best to hop over that repo's issue tracker.

**Comment by vizjerai** [comment]
@joeferner I'm the developer that @danschumann is talking about. We only need what is currently in the main repository to be released to npm.

**Comment by joeferner** [comment]
published v0.3.8
