### ISSUE TITLE
Getting compile error while installing node-oracledb on Windows7

### ISSUE THREAD

**Issue by sgarggit** [joeferner/node-oracle#253]
Hi ,
I ma getting following error while installing node-oracledb 

     Creating library C:\Users\sgarg\AppData\Roaming\npm\node_modules\oracledb\
  build\Release\oracledb.lib and object C:\Users\sgarg\AppData\Roaming\npm\node
  _modules\oracledb\build\Release\oracledb.exp
njsConnection.obj : error LNK2001: unresolved external symbol "__declspec(dllim
port) class v8::Handle<class v8::Value> __cdecl node::MakeCallback(class v8::Ha
ndle<class v8::Object>,class v8::Handle<class v8::Function>,int,class v8::Handl
e<class v8::Value> * const)" (__imp_?MakeCallback@node@@YA?AV?$Handle@VValue@v8
@@@v8@@V?$Handle@VObject@v8@@@3@V?$Handle@VFunction@v8@@@3@HQAV23@@Z) [C:\Users
\sgarg\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxproj]
C:\Users\sgarg\AppData\Roaming\npm\node_modules\oracledb\build\Release\oracledb
.node : fatal error LNK1120: 1 unresolved externals [C:\Users\sgarg\AppData\Roa
ming\npm\node_modules\oracledb\build\oracledb.vcxproj]
gyp ERR! build error

Any suggestions are welcome

**Comment by cjbj** [comment]
@sgarggit If you are using node-oracledb and not node-oracle, can you close this issue and repost it on the correct repo https://github.com/oracle/node-oracledb ? You will need to post a LOT more detail about the OS, the Oracle libraries you have, how you installed them etc.

**Comment by sgarggit** [comment]
Thanks for pointing me to correct forum.
