### ISSUE TITLE
oracledb install error

### ISSUE THREAD

**Issue by Blurzz** [joeferner/node-oracle#271]
I already got Visual studio 2013 Python2.7,10 installed, set environment variables as the tutorial
But still got this error: 

`D:\Project\PermissionTest\aaaeikonapplication>npm install oracledb --save
> oracledb@1.10.1 install D:\Project\PermissionTest\aaaeikonapplication\node_mod
ules\oracledb
> node-gyp rebuild
D:\Project\PermissionTest\aaaeikonapplication\node_modules\oracledb>if not defin
ed npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  reb
uild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [D:\Project\PermissionTest\aaaeikonapplication\node_module
s\oracledb\build\oracledb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Project\PermissionTest\aaaeikonapplication\node_modules\oracledb
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open 'D:\Project\PermissionTe
st\aaaeikonapplication\node_modules\npm-debug.log\package.json'
npm WARN ENOENT ENOENT: no such file or directory, open 'D:\Project\PermissionTe
st\aaaeikonapplication\node_modules\build\package.json'
npm WARN EPACKAGEJSON aaaeikonapplication@1.0.8 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! oracledb@1.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.10.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\Project\PermissionTest\aaaeikonapplication\npm-debug.log`

I tried use `npm install oracle` or `npm install oracle --save` will got the same error.

**Comment by cjbj** [comment]
You posted to the wrong repo.  The correct repo is https://github.com/oracle/node-oracledb

If you are OK with 3rd party binaries, see https://github.com/oracle/node-oracledb/issues/18

**Comment by Blurzz** [comment]
Sorry for my mistake, thanks for your comment!

**Comment by Anantha-R** [comment]
Set the visual studio version which you have in your local to Npm by running below command.
npm config -g set msvs_version 2015
