### ISSUE TITLE
Connecting to OracleDB using SID fails

### ISSUE THREAD

**Issue by anshulgupta0411** [joeferner/node-oracle#272]
I am trying to connect using SID and getting the below error 

**Error getting the connection - Error: ORA-12545: Connect failed because target host or object does not exist**
I have tried following connect strings : 

HOST:1521:SID
HOST:1521/SID

I am able to connect successfully using the SERVICE NAME.

Could you please help ?

**Comment by cjbj** [comment]
The 'easy connect' syntax uses Service Names not SIDs.

Also this node-oracle driver is not maintained (see the [README](https://github.com/joeferner/node-oracle/blob/master/README.md)).  Try using https://github.com/oracle/node-oracledb
There is some doc that will help with either driver in https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionhandling

**Comment by anshulgupta0411** [comment]
As per @cjbj recommendation, using node-oracledb.
