### ISSUE TITLE
Mac OS X image not found

### ISSUE THREAD

**Issue by alexzielenski** [joeferner/node-oracle#43]
Spent hours trying to finally get this to build and when I did and tried to run it I get the error "Reason: image not found" because the module seems to be looking in a very obscure location for my libraries:

```
module.js:356
  Module._extensions[extension](this, filename);
                           ^
Error: dlopen(/Users/Alex/Documents/Source/Web/oracletest/node_modules/oracle/build/Release/oracle_bindings.node, 1): Library not loaded: /ade/b/2649109290/oracle/rdbms/lib/libocci.dylib.11.1
  Referenced from: /Users/Alex/Documents/Source/Web/oracletest/node_modules/oracle/build/Release/oracle_bindings.node
  Reason: image not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Alex/Documents/Source/Web/oracletest/node_modules/oracle/lib/oracle.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I am running OS 10.8.3 and using node v0.10.8

**Comment by jhonyourangel** [comment]
i have the same problem but this fix DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Users/AiU/opt/oracle/instantclient/libs" node app.js does not work for me.

Can you help me up ?

lapdev04:Bucky AiU$ DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Users/AiU/opt/oracle/instantclient/libs" node app.js

/Users/AiU/node_modules/oracledb/lib/oracledb.js:30
    throw err;
          ^
Error: dlopen(/Users/AiU/node_modules/oracledb/build/Release/oracledb.node, 1): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1
  Referenced from: /Users/AiU/node_modules/oracledb/build/Release/oracledb.node
  Reason: image not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/AiU/node_modules/oracledb/lib/oracledb.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
lapdev04:Bucky AiU$

**Comment by ajbstudent** [comment]
Hey did you figure this out? I'm having the same problem.

**Comment by cjbj** [comment]
Did you check the symbolic links needed to use Instant Client?

**Comment by ajbstudent** [comment]
Hm I think I got those right. I'm on OSX 10.10.4 This is what i have in /opt/oracle/instantclient_11_2/

drwxrwxrwx  17 root  wheel   578B Jul  6 22:02 ./
drwxr-xr-x   5 root  wheel   170B Jul  1 14:03 ../
-rw-rw-rw-@  1 root  wheel   484B Apr 10  2014 BASIC_README
-rwxrwxrwx@  1 root  wheel    14K Apr 10  2014 adrci*
-rwxrwxrwx@  1 root  wheel    40K Apr 10  2014 genezi*
lrwxr-xr-x   1 Alex  wheel    20B Jul  6 16:36 libclntsh.dylib@ -> libclntsh.dylib.11.1
-r-xr-xr-x@  1 root  wheel    63M Feb  7  2014 libclntsh.dylib.11.1*
-r-xr-xr-x@  1 root  wheel   2.7M Jan 29  2014 libnnz11.dylib*
lrwxr-xr-x   1 Alex  wheel    18B Jul  6 22:02 libocci.dylib@ -> libocci.dylib.11.1
-r-xr-xr-x@  1 root  wheel   1.8M Feb  7  2014 libocci.dylib.11.1*
-rwxrwxrwx@  1 root  wheel   113M Apr 10  2014 libociei.dylib*
-r-xr-xr-x@  1 root  wheel   155K Jan  7  2014 libocijdbc11.dylib*
-r--r--r--@  1 root  wheel   2.0M Jan 28  2014 ojdbc5.jar
-r--r--r--@  1 root  wheel   2.6M Jan 28  2014 ojdbc6.jar
drwxrwxrwx@  7 root  wheel   238B Apr 10  2014 sdk/
-rwxrwxrwx@  1 root  wheel   159K Apr 10  2014 uidrvci*
-r--r--r--@  1 root  wheel    65K Jan  7  2014 xstreams.jar

and this is in my bash profile:

# OracleDB install settings
export PATH=/opt/oracle/instantclient_11_2:$PATH
export ORACLE_HOME=/opt/oracle/instantclient_11_2
#export DYLD_FALLBACK_LIBRARY_PATH=$ORACLE_HOME
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export LD_LIBRARY_PATH=$ORACLE_HOME:$LD_LIBRARY_PATH
export OCI_LIB_DIR=$ORACLE_HOME
export OCI_INC_DIR=$ORACLE_HOME/sdk/include

**Comment by cjbj** [comment]
You are seeing the 'obscure' /ade/... directory because PATH is not correct, or not set at the right time for your process, or the libraries the driver is looking for are not found.

Check the instructions again; I'm not an expert on Joe's node-oracle install so I can't comment much.  I can see you've a mix of odd things, such as OCI_INC_DIR which is for the other driver https://github.com/oracle/node-oracledb You also have things set that I would only have set for installation, not runtime.  And you have things set that are for Linux.  Finally I'm never a fan of setting ORACLE_HOME for an Instant Client, since that overloads the meaning of ORACLE_HOME.

**Comment by ajbstudent** [comment]
Ok thanks for the help! I should be able to sort it out.

**Comment by prajmehta** [comment]
Regarding the obscure paths ... those apparently came when the driver was compiled by the
developer of the driver (there has to be a better way of compiling, no?)

The following script should fix the paths:

#!/bin/sh
# script to change the dynamic lib paths and ids for oracle instant client
# exes and libs

# proces all the executable files in this directory
find . -maxdepth 1 -type f \( -perm -1 -o \( -perm -10 -o -perm -100 \) \) -print | while read exe
do
    echo adjusting executable $exe
    baseexe=`basename $exe`
    otool -L $exe | awk '/oracle/ {print $1}' | while read lib
    do
        echo adjusting lib $lib
        baselib=`basename $lib`
        if [ "$baseexe" = "$baselib" ]
        then
            echo changing id to $baselib for $exe
            install_name_tool -id $baselib $exe
        else
            echo changing path id for $lib in $exe
            install_name_tool -change $lib @executable_path/$baselib $exe
        fi
    done
done

**Comment by ajbstudent** [comment]
Hey I figured this out. I was running a node process using 'sudo -E node' but my DYLD_LIBRARY_PATH wasn't included in the environment! So strange. Just had to manually include it. Thanks!

**Comment by bjouhier** [comment]
Use `sudo -E`

sudo does not preserve environment variables by default because this is a risk on security.
