### ISSUE TITLE
Error : ORA-21561 OID generation failed

### ISSUE THREAD

**Issue by hkjang** [joeferner/node-oracle#47]
i had this error message
how can i solve that ?

Error : ORA-21561 OID generation failed

OCI_INCLUDE_DIR="/opt/instantclient/sdk/include/"
OCI_LIB_DIR="/opt/instantclient"
ORACLE_HOME="/opt/instantclient"

$ uname -a
Linux xxxxxx2.6.18-348.4.1.el5 #1 SMP Fri Mar 22 05:41:51 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Red Hat Enterprise Linux Server release 5.9 (Tikanga)
Kernel \r on an \m

$ gcc --version
gcc (GCC) 4.6.2
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by muki-buki** [comment]
thanks raztus, your solution fixed it for me

**Comment by frankbecker** [comment]
I got rid on the issue by adding "hostname": "127.0.0.1" to the connection object.

**Comment by ppot** [comment]
+1 for @raztus

**Comment by espositot** [comment]
What if you run into this issue -- OID generation error -- when you are trying to connect from your Web server to your database server?  The 'hostname' issue does not resolve the problem.

**Comment by lreisoliveira** [comment]
+1 for @raztus

**Comment by raks81** [comment]
+1 for @raztus and @cyates81 
It appears that the step in @raztus's reply is needed even if you are connecting to a remote DB.

**Comment by oursonvie** [comment]
Sorry I have to bother you guys, but I've been trial and error on the subject for days now. 
There is my problem, I've followed the installation guide for mac on "https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx" but every time I try the example JS i got "ORA-21561: OID generation failed"
I also tried on ubuntu 14.04 which is working fine, even on a MacBook air. 

Now I have been deleting and reinstalling oracle instant client, i tried basic and lite trying to get oracledb work, but no luck

**Comment by cjbj** [comment]
You are using node-oracledb which is not this repo.  It is https://github.com/oracle/node-oracledb

I haven't seen this on OS X but the general Linux solution is [given above](https://github.com/joeferner/node-oracle/issues/47#issuecomment-38309484).

**Comment by oursonvie** [comment]
Sorry about that, I've been using ip address directly
However the host fix worked, problem solved thanks

**Comment by GeraldoMilagre** [comment]
Hy guys, this issue can also be cause by wrong permissions on /etc/hosts file. If it is not readable for oracle uid the errors will show up.

Make sure your /etc/hosts is readable by everybody:

ls -l /etc/hosts
-rw-r--r-- 1 root system 7446 Mar 28 23:03 /etc/hosts

**Comment by cyarbrough22** [comment]
I've been working on this issue all day. This finally worked for me. Thank you!
