### ISSUE TITLE
error while installing oracle package on windows 7

### ISSUE THREAD

**Issue by vishalshivnath** [joeferner/node-oracle#83]
getting following error while installing oracle package 

C:\Users>npm install oracle
npm WARN package.json mongo@0.1.0 No repository field.
npm http GET https://registry.npmjs.org/oracle
npm http 304 https://registry.npmjs.org/oracle

> oracle@0.3.4 install C:\Users\vishaltyagi\node_modules\oracle
> node-gyp rebuild

C:\Users\vishaltyagi\node_modules\oracle>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:118:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:81:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vishaltyagi\node_modules\oracle
gyp ERR! node -v v0.10.18
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by Subha** [comment]
I followed all the instructions but still getting the same error. I am running the npm install oracledb from C:\.

I have my environment variables set :

OCI_LIB_DIR=C:\Oracle\instantclient_12_1
OCI_INCLUDE_DIR=C:\Oracle\instantclient_12_1\sdk\include


I am using nodejs version 0.10.38
Still same issue:

c:\>npm install oracle
|
> oracle@0.3.8 install c:\node_modules\oracle
> node-gyp rebuild


c:\node_modules\oracle>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  connection.cpp
  oracle_bindings.cpp
  executeBaton.cpp
  reader.cpp
c:\node_modules\oracle\src\connection.h(11): fatal error C1083: Cannot open inc
lude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\or
acle_bindings.vcxproj]
  statement.cpp
c:\node_modules\oracle\src\connection.h(11): fatal error C1083: Cannot open inc
lude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\or
acle_bindings.vcxproj]
c:\node_modules\oracle\src\connection.h(11): fatal error C1083: Cannot open inc
lude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\or
acle_bindings.vcxproj]
  outParam.cpp
c:\node_modules\oracle\src\executeBaton.h(12): fatal error C1083: Cannot open i
nclude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\
oracle_bindings.vcxproj]
c:\node_modules\oracle\src\connection.h(11): fatal error C1083: Cannot open inc
lude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\or
acle_bindings.vcxproj]
c:\node_modules\oracle\src\connection.h(11): fatal error C1083: Cannot open inc
lude file: 'occi.h': No such file or directory [c:\node_modules\oracle\build\or
acle_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\node_modules\oracle
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! oracle@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracle@0.3.8 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracle"
npm ERR! cwd c:\
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Any help is really appreciated.

Thanks
Rajan
